input_site/urls.py
from django.urls import path

from . import views

app_name = "input_site"

urlpatterns = [
    # Home page
    path("", views.index, name='index'),
    # Page containing threads
    path("threads/", views.threads, name='threads'),
    # The full page for a thread
    path('threads/<int:thread_id>/', views.thread, name='thread'),
    # Page for creating a new thread
    path('new_thread/', views.new_thread, name='new_thread'),
    # Page for adding new comments
    path('new_comment/<int:thread_id>/', views.new_comment, name='new_entry'),
    # About page
    path("about/", views.about, name='about'),
    # delete button
    path("delete/<int:thread_id>", views.delete, name='delete'),

]

mindyourmind/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("users/", include('users.urls')),
    path('', include("input_site.urls")),
]

users/urls.py
"""Define URL patterns for user"""

from django.urls import path, include
from . import views

app_name = 'users'
urlpatterns = [
    # Include default auth urls
    path('', include('django.contrib.auth.urls')),
    # Registration path
    path('register/', views.register, name='register'),
]

input_site/models.py
from django.db import models
from django.contrib.auth.models import User

class Thread(models.Model):
    """A new thread that contains a title, info, and comments"""
    title = models.CharField(max_length=200)
    text = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)
    owner = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__ (self):
        return self.text
    
class Comment(models.Model):
    thread = models.ForeignKey(Thread, on_delete=models.CASCADE)
    text = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)
    owner = models.ForeignKey(User, on_delete=models.CASCADE)

    class Meta:
        verbose_name_plural = "comments"
    def __str__(self):
        return f"{self.text[:50]}..."

users/models.py
from django.db import models

# Create your models here.

input_site/forms.py
from django import forms

from .models import Thread, Comment

class ThreadForm(forms.ModelForm):
    class Meta:
        model = Thread
        fields = ['title', 'text']
        labels = {'text':''}

class CommentForm(forms.ModelForm):
    class Meta:
        model= Comment
        fields = ['text']
        labels = {'text': 'comment:'}
        widgets = {'text': forms.Textarea(attrs={'cols':80})}

input_site/views.py
from django.shortcuts import render, redirect
from .models import Thread
from .forms import ThreadForm, CommentForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.shortcuts import redirect
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse

def index(request):
    return redirect(reverse("input_site:about"))

def threads(request):
    """Show all threads"""
    threads = Thread.objects.order_by('date_added')
    
    context = {'threads': threads}
    return render(request, 'input_site/threads.html', context)
@login_required
def thread(request, thread_id):
    """Show the complete page for a single thread"""
    thread = Thread.objects.get(id=thread_id)
    if request.method != 'POST':
        # No data submitted
        form = CommentForm()
    else:
        # POST data submitted; proccess data
        form = CommentForm(data=request.POST)
        if form.is_valid():
            new_comment = form.save(commit=False)
            new_comment.owner=request.user
            new_comment.thread = thread
            new_comment.save()
            return redirect("input_site:thread", thread_id=thread_id)
    comments = thread.comment_set.order_by("-date_added")
    context = {'thread': thread, 'form':form, "comments": comments}
    return render(request,'input_site/thread.html', context)

@login_required
def new_thread(request):
    """Add a new thread"""
    if request.method != 'POST':
        # No data submitted
        form = ThreadForm()
    else:
        # POST data submitted; proccess data
        form = ThreadForm(data=request.POST)
        if form.is_valid():
            new_thread = form.save(commit=False)
            new_thread.owner=request.user
            new_thread.save()
            return redirect('input_site:threads')
    # Display a blank or invalid form
    context = {'form':form}
    return render(request, 'input_site/new_thread.html', context)

def new_comment(request, thread_id):
    """Add a new comment under a thread or comment"""
    thread = Thread.objects.get(id=thread_id)

    if request.method != 'POST':
        # No data submitted
        form = CommentForm()
    else:
        # POST data submitted; proccess data
        form = CommentForm(data=request.POST)
        if form.is_valid():
            new_comment = form.save(commit=False)
            new_comment.thread = thread
            new_comment.save()
            return redirect("input_site:thread", thread_id=thread_id)
    # Display a blank or invalid form
    context = {"thread": thread, 'form':form}
    return render(request, 'input_site/new_comment.html', context)

def about(request):
    return render(request, 'input_site/about.html')

def delete(request, id):
  discussion = Thread.objects.get(id=id)

  #thread.delete()
  return render(request, 'input_site/delete.html')

users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm

def register(request):
    """Register a new user"""
    if request.method != 'POST':
        # Display a blank registration form
        form = UserCreationForm()
    else:
        # Process completed form
        form = UserCreationForm(data=request.POST)

        if form.is_valid():
            new_user = form.save()
            # Log the user in and then redirect to home page
            login(request, new_user)
            return redirect('input_site:index')
        
    # Display a blank or invalid form
    context = {'form': form}
    return render(request, 'registration/register.html', context)

input_site/templates/input_site/about.html
{% extends "input_site/base.html" %}
{% load bootstrap4 %}

{% block page_header %}
    <h1>About</h1>
{% endblock page_header %}

{% block content %}
    <p>mindyourmind exists in the space where mental health, wellness, engagement and 
        technology meet. We work with young people aged 14 to 29 to co-create interactive 
        tools and innovative resources to build capacity and resilience.</p>
    <br></br>

    <p>Nearly half of all youth have suffered from some sort of mental illness in their lives. This trend is only growing so it is 
        we strive to help reverse this problem. 
    </p>
    <br></br>
    <p>mindyourmind discussions is a platform that enables users to discuss issues and possible
        solutions in an open setting. To contribute to the conversation, create an account.
    </p>

    <br></br>
    <h3>FAQ</h3>
    <h5>Why did we create mindyourmind discussions?</h5>
    <p>Mindyourmind discussions aims to make it easier for us to continue our philosiphy of having
        young people's input involved in our projects. Through easy and open discussions, we create an enviornment
        that allows for collaberation, critical thinking, and most importantly, problem solving.
    </p>
    <li>an estimated 50% of youth have struggled with some form of mental illness in their lives</li>
    <li>Schools that don't take mental health of students seriously result in being one of the biggest causes for anxiety and deppression in adolesents</li>
    <br></br>
    <br></br>
    <a href="https://mindyourmind.ca/">The offical mindyourmind website</a>


{% endblock content %}

input_site/templates/input_site/base.html
{% load bootstrap4 %}

<!doctype html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <title>MindYourMind Discussions</title>

        {% bootstrap_css %}
        {% bootstrap_javascript jquery='full' %}
    </head>
    <body>
        <nav class="navbar navbar-expand-md navbar-light bg-light mb-4 border">
            <a class="navbar-brand" href="{% url 'input_site:index' %}">Discussions</a>

            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse"
                aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span></button>
        <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'input_site:threads' %}"></a></li>
                </li>
            </ul>
            <ul class="navbar-nav ml-auto">
                </li>
                    <li class="nav-item">
                    <a class="nav-link" href="{% url 'input_site:about' %}">About</a>
                </li>
                {% if user.is_authenticated %}
                        <li class="nav-item">
                        <a class="nav-link" href="{% url 'users:logout' %}">Log out</a>
                    </li>
                {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'users:register' %}">Register</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'users:login' %}">Log in</a>
                    </li>
                {% endif %}

            </ul>
        </div>
        </nav>

    <main role="main" class="container">
        <div class="pb-2 mb-6 border-bottem">
            {% block page_header %}{% endblock page_header %}
        </div>
        <div>
            {% block content %}{% endblock content %}
        </div>
    </main>
        
</body>
</html>

input_site/templates/input_site/index.html
{% extends "input_site/base.html" %}

{% block content %}
<head>
<meta http-equiv="refresh" content="0; {% url input_site:abouts %}" />
</head>
{% endblock content %}

input_site/templates/input_site/new_thread.html
{% extends "input_site/base.html" %}
{% load bootstrap4 %}

{% block page_header %}
    <h3>Add a new discussion</h3>
{% endblock page_header %}

{% block content %}

    <form action="{% url 'input_site:new_thread' %}" method='post'>
        {% csrf_token %}
        {% bootstrap_form form %}
        {% buttons %}
            <button name="submit" class="btn btn-primary">Post</button>
        {% endbuttons %}
    </form>
{% endblock content %}

input_site/templates/input_site/thread.html
{% extends "input_site/base.html" %}    
{% load bootstrap4 %}

{% block page_header %}
    <h3>{{ thread.title }}</h3>
    <p>{{ thread.text }}</p>   
{% endblock page_header %}

{% block content %}

    <form action="{% url 'input_site:thread' thread.id %}" method='post' class="form">
        {% csrf_token %}
        {% bootstrap_form form %}
        {% buttons %}
            <button name='submit' class="btn btn-primary">Add comment</button>
        {% endbuttons %}
    </form>

    <ul>
        {% for comment in comments %}
            <div class="card mb-3">
                <h4 class="card-header">
                    <p>{{ comment.owner }} posted on </p>{{ comment.date_added|date:'M d, Y H:i' }}
                </h4>
                <div class="card-body">
                    {{ comment.text|linebreaks }}
                </div>
            </div>
            <br></br>
        {% empty %}
            <li>Looks like there aren't any comments yet. Start the conversation by adding a comment!</li>
        {% endfor %}
    </ul>

{% endblock content %}

input_site/templates/input_site/threads.html
{% extends "input_site/base.html" %}

{% block page_header %}
    <h1>Discussions</h1>
{% endblock page_header %}

{% block content %}
    <h3><a href="{% url 'input_site:new_thread' %}">Create a discussion </a></h3>
    <ul>
        {% for thread in threads %}
            <div class="card mb-3">
                <h4 class="card-header">
                    <a href="{% url 'input_site:thread' thread.id %}">{{ thread.title }}</a> <small>   {{ thread.date_added|date:'M d, Y H:i' }}</small>
                </h4>
            <div class="card-body">
                {{ thread.text|linebreaks }}
            </div>
        {% empty %}
            <li><h3>Looks like something went wrong!</h3></li>
        {% endfor %}
    </ul>

{% endblock content %}